version: '3.7'
services:
  api:
    build: http_api/.
    tty: true
    depends_on:
      - worker
    links:
      - redis
    volumes:
      - "./http_api:/usr/src/app"
    environment:
      - FLASK_APP=wsgi.py
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
  worker:
    build: worker/.
    tty: true
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./worker:/usr/src/app"
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis

